name: Minecraft Mod CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x gradlew

      # 关键修改点 ▼ 添加 -x test 跳过测试
      - name: Build with Gradle (Skip Tests)
        run: ./gradlew build -x test --stacktrace

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: mod-build
          path: build/libs/*.jar
